# Generated by Django 5.2.4 on 2025-07-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('date', models.DateField()),
            ],
            options={
                'unique_together': {('currency', 'date')},
            },
        ),
    ]
